In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [ ]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)  # (3,6)
print(C)


---
# VIDEO: Matrix addition and subtraction
---


In [ ]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)


---
# VIDEO: Matrix-scalar multiplication
---


In [ ]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


In [ ]:
# test for some random MxN matrics whether s(A+B) = sA+sB - Yes
# in another word: whether the matrix-scalar multiplication a linear operation?

s = 2
m = 7
n = 5

A = np.random.randn(m,n)
B = np.random.randn(m,n)

% compute both sides of the equation
resL = s * (A+B)
resR = s*A + s*B

print(resR - resL) # 0


# VIDEO: Transpose

In [ ]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # normal transpose - only use for np array
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M)) # normal transpose - same as M.T, not only for np array

In [ ]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')             # normal transpose - same as C
print(np.transpose(C)), print('') # normal transpose - same as C

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
# use np.matrix to convert np array to matrix object
print(np.matrix(C).H) # note the sign flips! 



---
# VIDEO: Diagonal and trace
---


In [ ]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

In [ ]:
# the linearity of trace

# determine the relationship between tr(A) + tr(B) and tr(A+B)
# trace is only for square matrix

m = 5
n = 5
A = np.round(5*np.random.randn(m,n))
B = np.round(5*np.random.randn(m,n))

a = np.trace(A)+np.trace(B)
b = np.trace(A+B)
disp([a b])

# determine the relationship between tr(l*A) and l*tr(A)
l = 10
c = np.trace(l*A)
d = l*np.trace(A)

disp([c d])


---
# VIDEO: Broadcasting matrix arithmetic
---


In [2]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [6]:
# broadcast on the rows
print(A+r), print(' ')

# broadcast on the columns
# print(A+c) - does not work
# transform c into a column vector
print(np.reshape(c,(len(c),1)))
print(' ')

print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[100]
 [200]
 [300]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
